  - name: Make sure periodic.conf exists
    file:
      path: /etc/periodic.conf
      owner: root
      group: wheel
      mode: 0640
      state: touch
  - name: Add periodic emails
    lineinfile:
      dest: /etc/periodic.conf
      line: "{{ item }}_output={{ admin_email }}"
    with_items:
      - hourly
      - daily
      - weekly
      - monthly
      - security
