---
- name: add new SHA256 TLSA for certficate
  lineinfile:
    path: /usr/local/etc/nsd/zones/{{ cert.name | regex_replace('.*\.(\w+\.\w+)$', '\1')}}
    regexp: '^_{{ item.port }}\._{{ item.proto }}\.{{ cert.name }}\.\sTLSA\s[0-3]\s[0-3]\s1'
    line: "_{{ item.port }}._{{ item.proto }}.{{ cert.name }}. TLSA 3 0 1 {{ lookup('file', '/usr/local/etc/ansible_files/certs/{{ cert.name }}_tlsa.256') }}"
  with_items: "{{ cert.tlsa }}" 
  delegate_to: "{{ groups.master[0] }}"
  notify: updated zone on master

- name: add new SHA256 TLSA for certficate alt names
  lineinfile:
    path: /usr/local/etc/nsd/zones/{{ cert.name | regex_replace('.*\.(\w+\.\w+)$', '\1')}}
    regexp: '^_{{ item.1.port }}\._{{ item.1.proto }}\.{{ item.0 }}\.\sTLSA\s[0-3]\s[0-3]\s1'
    line: "_{{ item.1.port }}._{{ item.1.proto }}.{{ item.0 }}. TLSA 3 0 1 {{ lookup('file', '/usr/local/etc/ansible_files/certs/{{ cert.name }}_tlsa.256') }}"
  with_nested: 
    - "{{ cert.alt_names }}"
    - "{{ cert.tlsa }}"
  when: cert.alt_names is defined
  delegate_to: "{{ groups.master[0] }}"
  notify: updated zone on master

- name: add new SHA512 TLSA for certficate
  lineinfile:
    path: /usr/local/etc/nsd/zones/{{ cert.name | regex_replace('.*\.(\w+\.\w+)$', '\1')}}
    regexp: '^_{{ item.port }}\._{{ item.proto }}\.{{ cert.name }}\.\sTLSA\s[0-3]\s[0-3]\s2'
    line: "_{{ item.port }}._{{ item.proto }}.{{ cert.name }}. TLSA 3 0 2 {{ lookup('file', '/usr/local/etc/ansible_files/certs/{{ cert.name }}_tlsa.512') }}"
  with_items: "{{ cert.tlsa }}"
  delegate_to: "{{item}}"
  with_items: "{{groups['master']}}"
  notify: updated zone on master
    
- name: add new SHA512 TLSA for certficate alt names
  lineinfile:
    path: /usr/local/etc/nsd/zones/{{ cert.name | regex_replace('.*\.(\w+\.\w+)$', '\1')}} 
    regexp: '^_{{ item.1.port }}\._{{ item.1.proto }}\.{{ item.0 }}\.\sTLSA\s[0-3]\s[0-3]\s2'
    line: "_{{ item.1.port }}._{{ item.1.proto }}.{{ item.0 }}. TLSA 3 0 2 {{ lookup('file', '/usr/local/etc/ansible_files/certs/{{ cert.name }}_tlsa.512') }}"
  with_nested: 
    - "{{ cert.alt_names }}"
    - "{{ cert.tlsa }}"
  when: cert.alt_names is defined
  delegate_to: "{{item}}"
  with_items: "{{groups['master']}}"
  notify: updated zone on master
